### ISSUE TITLE
This app does not appear in any of my application lists.

### ISSUE THREAD

**Issue by LionsSharks15** [sandsmark/selectdefaultapplication#1]
I am on Manjaro 20.1, and this app does not appear in any of my application lists for Gnome or KDE. I have to specifically type in the command "selectdefaultapplication" to start the program.

**Comment by sandsmark** [comment]
I don't have any .desktop file for it, so gnome nor kde knows about it.

**Comment by sandsmark** [comment]
Fixed with https://github.com/sandsmark/selectdefaultapplication/commit/f7bc6c09b4878e0f2ed4dc95baab092069705cb1 + https://aur.archlinux.org/cgit/aur.git/commit/?h=selectdefaultapplication-git&id=70dc121c93ec9e6c97c37bf73cdf29a24309c0c5
